# Generated by Django 5.1.6 on 2025-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='bonus',
            new_name='net_salary',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='deductions',
            new_name='pension_deduction',
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='salary_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='payment_date',
        ),
    ]
