# Generated by Django 5.1.6 on 2025-02-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_rename_bonus_payroll_net_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='pension_deduction',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='salary_paid',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='tax_deduction',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='year',
        ),
        migrations.AddField(
            model_name='payroll',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
