# Generated by Django 5.1.6 on 2025-02-26 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('class_levels', models.ManyToManyField(related_name='subjects', to='academics.classlevel')),
                ('teachers', models.ManyToManyField(limit_choices_to={'role': 'teacher'}, related_name='subjects_taught', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
