# Generated by Django 5.1.6 on 2025-02-26 19:24

import django.db.models.deletion
import transport.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_transportfee_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='license_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportfee',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=20),
        ),
    ]
